### ISSUE TITLE
Steam Integration

### ISSUE THREAD

**Issue by JakeZim** [JakeZim/Conquerors#10]
Research it.
- How to get into their greenlight
- Achievements
- Inventory? can we utilize it
- Other integration things

**Comment by gusgalarnyk** [comment]
I just did the research for this and TL:DR we should wait a bit before we consider jumping in. Greenlight costs 100 dollars and can be used for both getting community feedback and getting our game distributed. After (if) that happens we then can integrate the steamworks SDK which will give us access to all of their nice things (workshop, inventory, networking I think). With that being said this should be something we consider after we have a functional game, we feel like we should continue developing and polishing, and then we can release it to green light to gain a following.
